### PR TITLE
Fix Docker file path

### PR DESCRIPTION
**Pull request by DRSchlaubi**

### CODE REVIEW

**Comment by jctaveras** [comment]
Hey @DRSchlaubi [the issue with the Dockerfile Path] #8  has been addressed on this [PR](https://github.com/jctaveras/heroku-deploy/pull/15/files). I'll be closing this PR and you can use the new version [v2.1.2](https://github.com/marketplace/actions/deploy-docker-image-to-heroku-app)

**Comment by DRSchlaubi** [comment]
This PR didn't fix it anyways as I found out

**Comment by jctaveras** [comment]
> This PR didn't fix it anyways as I found out

@DRSchlaubi I tried v2.1.2 and it worked for me 🤔 . I'd like to know if there is any project structure where this action wouldn't work.

**Comment by DRSchlaubi** [comment]
It didn't work here: https://github.com/DRSchlaubi/java8isancient/runs/2058355610

**Comment by jctaveras** [comment]
image

**Comment by jctaveras** [comment]
@DRSchlaubi I was able to reproduce the issue and I was able to apply the fix the version [v2.1.3](https://github.com/marketplace/actions/deploy-docker-image-to-heroku-app) should fix the issue

**Pull request closed without merging**
